name: Java CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout local repo code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Caches downloaded maven dependencies between builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path:  ~/.m2/repository
          key: ${{ runner.os }}-cache-${{ github.run_id }}${{ github.run_number }}
          restore-keys: ${{ runner.os }}-cache-

      # Set up  JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Maven Build
      - name: Build with Maven
        run: mvn -B clean verify
